Add Support for Syntax Highlighting
hackstream/zettel pull request #17
Opened 2020-09-16 08:16 UTC by athul

Uses Chroma for the Color ✨ 

The new config generates a new field called `pygmentsstyle`(just like Hugo 😉  ).

The only limitation I found is that you have to define the colorscheme in small letters. You can find all the styles [here](https://xyproto.github.io/splash/docs/).

Had to tweak the CSS a bit to give a better BG color of the code block

2020-09-16 08:19 UTC, mr-karan commented
`wing.css` is the framework we use. All the overrides should go to our custom stylesheet.

2020-09-16 08:41 UTC, athul commented
Oh Okay, Will Change that

2020-09-16 09:41 UTC, athul commented
e4aec4172b46cdd30e76e4011e194cc6853a0c21 changes the usage to custom sheet.

Here is an output for reference. Syntax Used: GitHub

![Screen Shot 2020-09-16 at 3 07 48 PM](https://user-images.githubusercontent.com/40897573/93320197-65e65780-f82e-11ea-9c43-c4e9bdc787ec.png)

2020-09-17 04:38 UTC, mr-karan requested changes

2020-09-17 04:38 UTC, mr-karan commented on internal/pipeline/utils.go
> +func SyntaxHighlighter(html []byte, syntaxStyle string) string {
Can you add some comments in this function, how does this really work?

2020-09-18 10:33 UTC, merged

2020-09-18 10:34 UTC, mr-karan commented
Thanks @athul  :+1: